import Header from "../components/Header";
import "./globals.css";


export const metadata = {
  title: "Listing Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className=""
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
